### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by Unknow0059** [DomDom3333/DesktopMode#1]
Sounds interesting but there's no readme explaining properly what it is.

**Comment by DomDom3333** [comment]
Fair. That is mostly because I haven't gotten far enough with it to justify writing one. In a few weeks I should be far enough to show it off. Had to overhaul some things. 

If you want to help, I can write one earlier

**Comment by Unknow0059** [comment]
I see. Though I don't know enough programming to be able to help.
